name: "Action-Badger"
description: "Add bagdes to PRs"
author: "René Fritze"
inputs:
  myInput:
    description: "Input to use"
    default: "world"
  repotoken:
    description: "Github Token"
    default: ""
outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
