name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest

        # Put your action repo here
        uses: renefritze/github-action-badger@master
        with:
          myInput: world
          repotoken: ${{ secrets.GITHUB_TOKEN }}
      - name: Check outputs
        run: |
          echo "${{ steps.selftest.outputs.myOutput }}"
